name: Recovery Build

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'Ссылка на манифест'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp'
      MANIFEST_BRANCH:
        description: 'Ветка манифеста'
        required: true
        default: 'twrp-14.1'
      DEVICE_TREE_URL:
        description: 'Ссылка на дерево устройства'
        required: true
        default: 'https://github.com/internetov-coder/twrp_ximi14t'
      DEVICE_TREE_BRANCH:
        description: 'Ветка дерева'
        required: true
        default: 'main'
      DEVICE_PATH:
        description: 'Путь (device/xiaomi/degas)'
        required: true
        default: 'device/xiaomi/degas'
      DEVICE_NAME:
        description: 'Имя устройства (degas)'
        required: true
        default: 'degas'
      MAKEFILE_NAME:
        description: 'Имя мейкфайла (twrp_degas)'
        required: true
        default: 'twrp_degas'
      BUILD_TARGET:
        description: 'Цель сборки (vendorboot)'
        required: true
        default: 'vendorboot'

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cleanup Disk Space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/boost /usr/local/lib/node_modules
        sudo docker image prune -a -f
        df -h

    - name: Prepare environment
      run: |
        sudo apt update
        sudo apt install -y gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses-dev \
            x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache \
            lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev libsdl1.2-dev build-essential libgtk-3-dev \
            libglu1-mesa-dev freeglut3-dev git libxml2 lzop pngcrush schedtool squashfs-tools imagemagick \
            libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses6 python3 tar

    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize repo
      run: |
        mkdir workspace
        cd workspace
        git config --global user.name "internetov-coder"
        git config --global user.email "internetov.dev@gmail.com"
        # Используем проверенный AOSP манифест 14.1
        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
      id: pwd

    - name: Repo Sync
      run: |
        repo sync -j$(nproc --all) --force-sync --no-tags --no-clone-bundle --current-branch
        # Проверим, реально ли она там (просто посмотрим в логах)
        ls -d system/security
      working-directory: workspace


    - name: Clone device tree
      run: |
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Building recovery
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        # Собираем с ap2a
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-ap2a-eng
        make clean
        make ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: | 
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*.zip
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/*vendor*.img
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Device: ${{ github.event.inputs.DEVICE_NAME }}
          Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
          Target: ${{ github.event.inputs.BUILD_TARGET }}.img
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
